adds nvm installation

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,5 +1,6 @@
 #!/usr/bin/env zsh
 
+# colors
 RED="\e[31m"
 GREEN="\e[32m"
 YELLOW="\e[33m"
@@ -102,6 +103,29 @@ else
   echo -e "${BLUE}Using node $(node --version) / npm $(npm --version)${NC}"
 fi
 
+# install nvm
+export NVM_DIR="$HOME/.nvm"
+# 2. Check if the NVM source file exists
+if [ -s "$NVM_DIR/nvm.sh" ]; then
+  # 3. If it exists, source the script to load the NVM functions
+  # Using a single dot (.) is a common shorthand for the 'source' command
+  . "$NVM_DIR/nvm.sh"
+
+  echo -e "${BLUE}Using nvm $(nvm --version)${NC}"
+else
+  echo -e "${WHITE}Installing nvm...${NC}"
+
+  if brew install nvm -q &> /dev/null; then
+    echo -e "${GREEN}Successfully installed nvm${NC}"
+    echo -e "${WHITE}Please restart your terminal to use it.${NC}"
+    exit 1
+  else
+    echo -e "${RED}Failed to install nvm${NC}"
+    exit 1
+  fi
+fi
+
+# install global npm packages
 NPM_EXECUTABLE="$(brew --prefix)/bin/npm"
 NPM_LIST_ARGS=(list -g --parseable)
 NPM_OUTDATED_ARGS=(outdated)
@@ -109,7 +133,6 @@ NPM_INSTALL_ARGS=(install -g --no-audit --no-fund --loglevel silent)
 NPM_UPDATE_ARGS=(update -g --no-audit --no-fund --loglevel silent)
 NPM_GEMINI_PACKAGE="@google/gemini-cli"
 
-# install global npm packages
 if ! command -v gemini &> /dev/null
 then
   echo -e "${WHITE}Installing Gemini CLI...${NC}"
@@ -148,3 +171,4 @@ else
 fi
 
 echo -e "${GREEN}Dev setup completed successfully${NC}"
+exit 0
