refactors several aspects of bin/setup and adds python3

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,29 +1,150 @@
 #!/usr/bin/env zsh
 
+RED="\e[31m"
+GREEN="\e[32m"
+YELLOW="\e[33m"
+BLUE="\e[34m"
+MAGENTA="\e[35m"
+CYAN="\e[36m"
+WHITE="\e[37m"
+NC="\e[0m" # No Color (Reset)
+
 # install homebrew
 if ! command -v brew &> /dev/null
 then
-  echo "Installing Homebrew..."
+  echo -e "${WHITE}Installing Homebrew...${NC}"
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
 else
-  echo "Upgrading Homebrew and updating packages..."
-  brew upgrade && brew update
+  echo -e "${WHITE}Updating Homebrew...${NC}"
+  brew update &> /dev/null
+fi
+
+# ensure brew bins are added to $PATH
+ZSHRC_FILE="$HOME/.zshrc"
+BREW_PREFIX_CMD='export PATH="$(brew --prefix)/bin:$PATH"'
+
+if grep -qF "$BREW_PREFIX_CMD" "$ZSHRC_FILE"; then
+    echo "The Homebrew PATH line already exists in $ZSHRC_FILE. No changes made."
+else
+    echo "" >> "$ZSHRC_FILE"
+    echo "# Add Homebrew bin to PATH" >> "$ZSHRC_FILE"
+    echo "$BREW_PREFIX_CMD" >> "$ZSHRC_FILE"
+    echo -e "${GREEN}Homebrew PATH line added to $ZSHRC_FILE.${NC}"
+    source "$HOME/.zshrc"
 fi
 
 # install homebrew packages (see Brewfile)
-echo "Installing homebrew packages..."
-brew bundle
+echo -e "${WHITE}Installing/upgrading all dependencies from the Brewfile...${NC}"
+brew bundle --upgrade -q
 
-# install ruby
+# install rbenv
 if ! command -v rbenv &> /dev/null
 then
-  echo "Installing Ruby and rbenv..."
-  # to list all latest stable releases: rbenv install -l
-  rbenv install 3.4.7 -s
-  rbenv global 3.4.7
+  echo -e "${WHITE}Installing rbenv...${NC}"
+  if brew install rbenv -q &> /dev/null
+  then
+    echo -e "${GREEN}Successfully installed rbenv${NC}"
+  else
+    echo -e "${RED}Failed to install rbenv${NC}"
+    exit 1
+  fi
 else
-  echo "Using ruby `rbenv version` and `rbenv --version`"
+  echo -e "${BLUE}Using $(rbenv --version)${NC}"
 fi
 
-# install global npm packages in package.json
-./bin/install-global-npm-deps.sh
+RUBY_VERSION=$(cat .ruby-version)
+
+# install ruby
+if rbenv version-name = "$RUBY_VERSION" &> /dev/null
+then
+  echo -e "${BLUE}Using ruby $(rbenv version-name)${NC}"
+else
+  echo -e "${WHITE}Installing ruby $RUBY_VERSION...${NC}"
+  if rbenv install $RUBY_VERSION -s && rbenv global $RUBY_VERSION &> /dev/null
+  then
+    echo -e "${GREEN}Successfully installed ruby $RUBY_VERSION via rbenv${NC}"
+  else
+    echo -e "${RED}Failed to install ruby $RUBY_VERSION via rbenv${NC}"
+    exit 1
+  fi
+fi
+
+# install python/pip3
+PYTHON_EXECUTABLE="$(brew --prefix)/bin/python3"
+if ! command -v $PYTHON_EXECUTABLE &> /dev/null
+then
+  echo -e "${WHITE}Installing python...${NC}"
+  if brew install python -q &> /dev/null
+  then
+    echo -e "${GREEN}Successfully installed python${NC}"
+  else
+    echo -e "${RED}Failed to install python${NC}"
+    exit 1
+  fi
+else
+  PYTHON_VERSION=$($PYTHON_EXECUTABLE -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')")
+  PIP_VERSION=$($PYTHON_EXECUTABLE -c "import pip; print(pip.__version__)")
+  echo -e "${BLUE}Using python $PYTHON_VERSION / pip $PIP_VERSION${NC}"
+fi
+
+# install node & npm (if now already installed from Brewfile)
+if ! command -v npm &> /dev/null
+then
+  echo -e "${WHITE}Installing npm...${NC}"
+  if brew install node -q &> /dev/null
+  then
+    echo -e "${GREEN}Successfully installed node/npm${NC}"
+  else
+    echo -e "${RED}Failed to install node/npm${NC}"
+    exit 1
+  fi
+else
+  echo -e "${BLUE}Using node $(node --version) / npm $(npm --version)${NC}"
+fi
+
+NPM_EXECUTABLE="$(brew --prefix)/bin/npm"
+NPM_LIST_ARGS=(list -g --parseable)
+NPM_OUTDATED_ARGS=(outdated)
+NPM_INSTALL_ARGS=(install -g --no-audit --no-fund --loglevel silent)
+NPM_UPDATE_ARGS=(update -g --no-audit --no-fund --loglevel silent)
+NPM_GEMINI_PACKAGE="@google/gemini-cli"
+
+# install global npm packages
+if ! command -v gemini &> /dev/null
+then
+  echo -e "${WHITE}Installing Gemini CLI...${NC}"
+  if $NPM_EXECUTABLE $NPM_INSTALL_ARGS $NPM_GEMINI_PACKAGE
+  then
+    echo -e "${GREEN}Successfully installed $NPM_GEMINI_PACKAGE${NC}"
+  else
+    echo -e "${RED}Failed to install $NPM_GEMINI_PACKAGE${NC}"
+    exit 1
+  fi
+else
+  OUTDATED_OUTPUT=$($NPM_EXECUTABLE $NPM_OUTDATED_ARGS $NPM_GEMINI_PACKAGE --json 2> /dev/null)
+  if [[ "$OUTDATED_OUTPUT" == *"$NPM_GEMINI_PACKAGE"* ]]
+  then
+    echo -e "${YELLOW}$NPM_GEMINI_PACKAGE is outdated${NC}"
+    echo -e "${WHITE}Updating Gemini CLI...${NC}"
+    if $NPM_EXECUTABLE $NPM_UPDATE_ARGS $NPM_GEMINI_PACKAGE
+    then
+      echo -e "${GREEN}Successfully updated $NPM_GEMINI_PACKAGE${NC}"
+    else
+      echo -e "${MAGENTA}Failed to npm update $NPM_GEMINI_PACKAGE. Manually removing current package directories to do clean install...${NC}"
+      # update failed due to permissions, remove gemini to install fresh
+      rm -rf $(which gemini)
+      rm -rf $($NPM_EXECUTABLE $NPM_LIST_ARGS $NPM_GEMINI_PACKAGE)
+      if $NPM_EXECUTABLE $NPM_INSTALL_ARGS $NPM_GEMINI_PACKAGE
+      then
+        echo -e "${GREEN}Successfully re-installed $NPM_GEMINI_PACKAGE${NC}"
+      else
+        echo -e "${RED}Failed to re-install $NPM_GEMINI_PACKAGE${NC}"
+        exit 1
+      fi
+    fi
+  else
+    echo -e "${BLUE}Using gemini $(gemini --version)${NC}"
+  fi
+fi
+
+echo -e "${GREEN}Dev setup completed successfully${NC}"
